In [1]:
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings('ignore')
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    %matplotlib inline
    import matplotlib.cm as cm
    from sklearn.decomposition import PCA
    from sklearn.manifold import TSNE

### Load the dataset

In [2]:
df = pd.read_csv('data.csv')
print(df.shape)
print(df.isnull().any().any()) ##check missing value
df.describe()

(107856, 266)
False

,Y,X0,X2,X3,X4,X5,X6,X8,X9,X11,...,X461,X462,X467,X468,X469,X470,X472,X475,X477,X478
count,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,...,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000,107856.000000
mean,0.615795,1.477952,59.556038,0.001261,0.017700,7.401025,0.282265,1.160102,0.038857,0.000195,...,0.001085,0.012099,0.000436,0.002531,0.036363,0.001140,0.078002,0.013509,0.008660,0.006323
std,0.213486,17.865485,2215.079392,0.035487,1.325519,98.190201,35.262728,32.956659,0.727419,0.063944,...,0.032918,0.109331,0.020871,0.050247,0.187193,0.033751,0.268176,0.115440,0.092654,0.079267
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.473684,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.777778,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,5727.000000,254212.000000,1.000000,419.000000,5299.000000,5516.000000,6725.000000,91.000000,21.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [3]:
df.head()

,Y,X0,X2,X3,X4,X5,X6,X8,X9,X11,...,X461,X462,X467,X468,X469,X470,X472,X475,X477,X478
0,0.074074,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.684211,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0.814815,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.814815,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0.421053,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Select the first 20,000 instance as our dataset
- We have normalized the first 20,000 instances in R, and stored in the scaled.csv

In [20]:
trainSet = pd.read_csv('scaled.csv')

print(trainSet.shape)
print(trainSet['Y'].nunique())

X=trainSet.drop(['Y'],axis=1).values
y=trainSet['Y']
trainSet.describe()

(20000, 260)
584

,Y,X0,X2,X3,X4,X5,X6,X8,X9,X12,...,X461,X462,X467,X468,X469,X470,X472,X475,X477,X478
count,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,...,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04,2.000000e+04
mean,1.744963e-11,-1.707460e-10,3.762456e-10,-7.799558e-11,8.454451e-11,1.642374e-10,2.566001e-10,2.432001e-10,-1.417081e-10,3.614370e-10,...,-4.352489e-10,-1.866000e-10,9.399661e-11,-4.274903e-10,2.738519e-10,3.043041e-10,2.263653e-10,-4.230015e-10,1.094010e-10,4.453120e-10
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-3.121950e+00,-4.071009e-01,-4.148077e-02,-2.550275e-02,-4.670227e-02,-1.436952e-01,-6.825969e-02,-2.267780e-02,-5.601406e-02,-1.618996e-01,...,-4.186861e-02,-7.071068e-03,-3.810555e-02,-3.875795e-02,-2.786402e-01,-4.362937e-02,-4.069751e-01,-1.704987e-01,-1.378531e-01,-8.212707e-02
25%,-5.054085e-01,-4.071009e-01,-4.148077e-02,-2.550275e-02,-4.670227e-02,-1.436952e-01,-6.825969e-02,-2.267780e-02,-5.601406e-02,-1.618996e-01,...,-4.186861e-02,-7.071068e-03,-3.810555e-02,-3.875795e-02,-2.786402e-01,-4.362937e-02,-4.069751e-01,-1.704987e-01,-1.378531e-01,-8.212707e-02
50%,2.042149e-01,-4.071009e-01,-4.148077e-02,-2.550275e-02,-4.670227e-02,-1.436952e-01,-6.825969e-02,-2.267780e-02,-5.601406e-02,-1.618996e-01,...,-4.186861e-02,-7.071068e-03,-3.810555e-02,-3.875795e-02,-2.786402e-01,-4.362937e-02,-4.069751e-01,-1.704987e-01,-1.378531e-01,-8.212707e-02
75%,7.453135e-01,2.693712e-01,-4.148077e-02,-2.550275e-02,-4.670227e-02,-1.163920e-01,-6.825969e-02,-2.267780e-02,-5.601406e-02,-1.618996e-01,...,-4.186861e-02,-7.071068e-03,-3.810555e-02,-3.875795e-02,-2.786402e-01,-4.362937e-02,-4.069751e-01,-1.704987e-01,-1.378531e-01,-8.212707e-02
max,1.523211e+00,3.341650e+01,7.016052e+01,3.920950e+01,9.335785e+01,7.136328e+01,5.104664e+01,1.406349e+02,2.015959e+01,6.607294e+01,...,2.388305e+01,1.414143e+02,2.624158e+01,2.579987e+01,3.588678e+00,2.291920e+01,2.457030e+00,5.864854e+00,7.253735e+00,1.217564e+01

## Data preprocessing

In [21]:
## preprocess Y, split it into two classes(0,1) according to their value
y_median=y.median()
print(y_median)
for i in range (y.size):
    if y[i]<=y_median: y[i]=0
    else: y[i]=1
print(y.value_counts())

0.204214927
0.0    10078
1.0     9922
Name: Y, dtype: int64
2

## Dimensionality reduction (PCA)
Source: Dimensionality reduction (PCA, tSNE) https://www.kaggle.com/code/tilii7/dimensionality-reduction-pca-tsne

In [7]:
##PCA
## n=10, 20, 25, 30
#n= 25
#pca = PCA(n_components = n, svd_solver = 'full', random_state = 1001)
#X_pca = pca.fit_transform(X)
#print('Explained variance: %.4f' % pca.explained_variance_ratio_.sum())

#print('Individual variance contributions:')
#for j in range(n):
#    print(pca.explained_variance_ratio_[j])